feat(Aurora): add Aurora Layer2 token list
DimensionDev/Mask-Token-List pull request #46
Opened 2021-12-27 22:03 UTC by developerfred

2022-01-08 05:51 UTC, UncleBill commented
Hi, @developerfred, thanks for you contribution. 
I would to know where the token list`src/erc20/aurora.json` comes from？I wanna do a double check.

2022-01-08 08:33 UTC, developerfred commented
- [maininet](https://mainnet.aurora.dev/tokens )
- [testmet](https://testnet.aurora.dev/tokens )
- [betanet](https://betanet.aurora.dev/tokens )

2022-01-09 10:22 UTC, UncleBill commented
@developerfred Thanks, I have confirmed the list now.

2022-01-09 10:22 UTC, UncleBill submitted a review, later dismissed

2022-01-11 06:42 UTC, UncleBill commented
Hi, @developerfred , you need to build out token-list. I already did it in
https://github.com/DimensionDev/Mask-Token-List/tree/feat/AuroraTokenList

you can sync your branch with it.

2022-01-11 10:49 UTC, developerfred commented
> `feat`/AuroraTokenList

I will do this.

2022-01-11 10:52 UTC, developerfred commented
@UncleBill done

2022-01-12 06:17 UTC, UncleBill approved these changes

2022-01-12 13:27 UTC, guanbinrui commented on src/erc20/aurora.json
> +    "tags": ["ethereum"]
Unused field? Please remove it.

2022-01-12 14:57 UTC, developerfred commented on src/erc20/aurora.json
> +    "tags": ["ethereum"]
OK!

2022-01-13 02:31 UTC, UncleBill submitted a review, later dismissed

2022-01-13 23:21 UTC, guanbinrui requested changes

2022-01-13 23:21 UTC, guanbinrui commented on package-lock.json
> +{
Delete this file.

2022-01-13 23:46 UTC, developerfred commented on package-lock.json
> +{
done

2022-01-14 00:12 UTC, guanbinrui approved these changes

2022-01-14 00:12 UTC, merged